apiVersion: v1
kind: Service
metadata:
    name: app-service
    labels: 
        app: demo-python-app
spec:
    ports:
        - protocol: TCP 
          port: 80
          targetPort: 5000 
    selector: 
        app: demo-python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
        app: demo-python-app
spec:
    replicas: 6
    selector:
        matchLabels:
            app: demo-python-app
    template:  
        metadata:
            labels:
                app: demo-python-app
        spec:
            containers:
            - name: python-app
              image: {{.Values.image}}
              ports:
                - containerPort: 5000 
            

